branches:
  only:
  - master
env:
  global:
  # BINTRAY_USER
  - secure: "CwnBsRPvPXJqAoGHMBPLx4eNeMVZiBZLry+PYAcDHo42n6e+0KD4DXdqxWcUjIbU7ndSzIO+ZuDHQAQ5XxTg2m2PxabLrHGJ+ABGLHg7MG541mB0Gwa+NQHLMH4pJXkFJIChMpq3jsA6Dj5gBdMA/FUwZKvNYH8xBohJvoYbCHI341H5HHmChYAgfL690EzmMb0LatcIpY+7hqRPsc/nBWOO3r9EYJHxcOeT2hLUF+Az4EaMKcryiFvRBbYdhS+54APrXMl5LA/Fx4cfupv18njKArBu04vGJ0unnD9uidR3K62j044dCVP2tIg3mQsraijAJYzwQk5uVMz4TtRyufgY+kw93FcKF9ROT2oILgdmYZpbqmiK1NBSh1/6vj4ve5fzakrkYc9QXmM3HbeSqwArfAC6D7fOhvJ2H4wjTk1eC9imB0tDcWm05FqV8wOFpZyDHCea+WOEgimXE3I1M3nYrII4mopFsKMTwWlGqjwcc880VnymP5Z7bPkwSKH7cqM4UHaOaGsL8rSRWOt8ayotZbdniNX1v+UtFFp1bnoqWddSKZAIKqx8RmlcgOAgoKrjBpPdCXFKqrBfBQzW8u5GEDDb5oYM3SprtVRlzRwTq8uCHvO+gFZb0qPDeEOLxwE2hXpOf5o5sqT5IVn4c09aEhFN/R+2n/izzjUtWBM="
  # BINTRAY_API_KEY
  - secure: "Bv9A4gmSwuy3F/ZsStIWn5DLfX3VB2B3LG8KDW0EbVW5NLeFjFmt/7QdQKOg6NmnCjk/gEswFdB5rQXL4hj3C1CadLM1LuS5oBDHHGQCIgkzlvWilbUGE+pa4rd6e5hOZvdefku0pIOVUygbrO9K2C2AJSKggB5ESSIBql1aJGLad5r6up85bteKXZo9BF+nZ/UqRBcg7sLDfNUk+JIyut3f5bbWLUZZ9ebiijiR4I45EOobF9rTO2cKLaILPgOs6r0YS53b/JHdbM4YNGvLocIY3sVrKp/FAO+4+BO7XDYs2whw2294JqFH7MCEe3OZjzp0f+VuApFh7KVOjc40PQXo3cYMp4a+zMTZjzGlRKZ2BP22vSvzTb0PuLNSl/V0ixfDICLB1UGIRHpRvoDm3BmD7D8FJODbhQRlU30gbf8OPFakSZXxLhdtztTk5vTQ9LiahdO9LV3EW4JJan97eFs3otN7rJVwZr7o93yHHbIm7MBg4+Z3e9/vYDWGfJWHecvVkZWs0Q6d9hgHxhO3A3uLlzc6hAqKPt4x1Vr7SaMa9gDVOywlZFMWm3XQ7chcc4aROJFalFinb7qaCmhLcQjbQnYWcClcEzdxLvl9Va4ZPR/KtuaL2b3qv5CResnC6Nkih/FgI8qsgd2iUP5KxTqwXDwSV/stfC+fEwyqvQQ="
  # GIT_USER
  - secure: "MLLyxTAUyOB1mDhOcInFKztTo5wClnvXUBKVp5rWEZ94tj8uS9suVjLbeiaTlqv3Vewlp7Us7XAqxfdpACg8J4qBU6O1Gdzh9ZvMR/0i6/lEsMFX0VjFVt3UrTycajm/PaTy2pDFgd8+GGAyogfFK4lEhC95VT5G8AXm2dC2D+B1g29DBqJdhB/hdACo7tTThL5D46c5+1BMnwfDILeAd++Wk7L2h44Ch7r+BsjsszaPXbLm5Y+9Ce1CDKwjFplfyY61Y9wj2CW4Ag1o67wYcsGJJArYpNBw9vQr46BFcO2KnHzO6PBYZKFW64rPoFY2jRKNaS+boyXzl9w8kb0NuZakvWuRjJ4lfvnMMYC+G+SXASqzK5UCrmX/h1i3pTZ/k97Vu/bgP5wryjX62V638jFuD5SeDBa7V8NSXtoRQSUVgum3gTk8ruy6HLzYhEqffLDVxCLzQrezx7MYQFJEywRvLf0KS7kPiQXdI3tSWnm2Jf9l8jyTcxUx5tF3u1LpCaFxP4eEPcim90Nn2yZzMA7aNTxgDf3b1xwYniT8fi2vwqO2MRvQb3AlimuE2DKrGQydYtTu9flx1+EwUBMSYRWyYWoXuUnAqilS4C3ejwVXKmtt2AMItiN+34i3mpKbwkPO3cz5wQN6U8SlZo7mWJy90jgQXIWHYNGCRIpbDJE="
  # GIT_API_KEY
  - secure: "okFAY1Nkg5+jZrElAj/7elMzo3bDjkHeCDw658yqGa1qs8+CLIb8XQvi07P+nYq6V0eUxXOcWzQOdFQjhVR8a7Gk3e8OGnkICJDudykybhUvfRQEq/4SdQH3dXJiyS+mmtCWSgLo0fP6dBacHgG/Jt/EwnI2aDB25MCl7vpfC8uX5Ck2GGU9yECJrYPRNmgW3pjoM/3aIjV6ajd+ywNBXjCKpaIjRFoaDvvTcWInG4fbLRFMQIf3AeoVW8VGvP8f5Ka373N7i3pu4P/dbSuB1e8HLHlk8DfeA89JEqedcIjHYnEvRszRVzhH5oNIyGnKqDBLQYMMqePVCow5S8JlHf7p4fsCZWwYytDWuFXBATpLaXli7aTSclZn4g6Ip6eCsuJLYc8jtWvgZ9PM7FJUpEITacCcOYP6pEMr+ZmaRnfTmagB5BPMtL3IBn1oQBHeL9bUEis6uw5sFF+gHT7QfgY5EeZuTMhnrPUt0SvhLKR9ExZ2uwNDXCZ2Y72+6DPQHFYHOmOcUEMv7Rl/vcU2Q1xunWFWvM/lr3qtmj10NCWQcFHAUeScatVEea4q/XeN98hmkz8alP/T+UtyCTmc58liOtalIM9V/wIt16+/d1IcgBDwAGf+R1mxV0ShZPLklvfzN55rvszI+xcaWtb78zdAywdfB/g/yI56NHm5E7o="
language: scala
scala:
- 2.11.11
- 2.12.2
jdk:
- oraclejdk8
cache:
  directories:
  - "~/.ivy2"
  apt: true
script:
- sbt -Dsbt.log.noformat=true -sbt-dir ~/.sbt ++$TRAVIS_SCALA_VERSION test
after_success:
- sh "$TRAVIS_BUILD_DIR/.travis.release.sh"
