version: 2.1

orbs:
  scala:
    executors:
      scala_executor:
        parameters:
          image:
            type: string
            default: circleci/openjdk:8-jdk
          dir:
            type: string
            default: ~/repo
          scala_version:
            type: string
            default: 2.11.12
        docker:
          - image: << parameters.image >>
        working_directory: << parameters.dir >>
        environment:
          SCALA_VERSION: << parameters.scala_version >>

    commands:
      restore_sbt_cache:
        steps:
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum ".circleci/config.yml" }}
                # Fallback to using the latest cache if no exact match is found
                - v1-dependencies-

      save_sbt_cache:
        steps:
          - save_cache:
              paths:
                - ~/.m2
                - ~/.ivy2/cache
                - target/resolution-cache
                - target/streams
                - project/target/resolution-cache
                - project/target/streams
              key: v1-dependencies-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum ".circleci/config.yml" }}

commands:
  test:
    steps:
      - checkout
      - scala/restore_sbt_cache
      - run:
          name: Check formatting with Scalafmt
          command: sbt ++$SCALA_VERSION scalafmtCheckAll
      - run:
          name: Compile
          command: sbt ++$SCALA_VERSION compile
      - scala/save_sbt_cache
      - run:
          name: Run unit and integration tests
          command: sbt ++$SCALA_VERSION test

  publish:
    steps:
      - checkout
      - scala/restore_sbt_cache
      - run:
          name: Publish Artifact
          command: .circleci/release.sh

jobs:
  test_211:
    executor:
      name: scala/scala_executor
      scala_version: 2.11.12
    steps:
      - test
  test_212:
    executor:
      name: scala/scala_executor
      scala_version: 2.12.8
    steps:
      - test
  test_213:
    executor:
      name: scala/scala_executor
      scala_version: 2.13.0
    steps:
      - test

  publish:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - publish


workflows:
  test_and_publish:
    jobs:
      - test_211:
          context: PagerDuty
      - test_212:
          context: PagerDuty
      - test_213:
          context: PagerDuty

      - publish:
          requires:
            - test_211
            - test_212
            - test_213
          context: PagerDuty
          filters:
            branches:
              only: master
